package com.yc.input.ui

import android.content.Context
import android.content.res.Configuration

/** 对齐参考效果.html 浅色 / 深色（夜间）调色板。 */
data class ThemeTokens(
    val keyboardBg: Int,
    val keyNormal: Int,
    val keyUtility: Int,
    val keyAccent: Int,
    val keyPressed: Int,
    val keyBorder: Int,
    val keySpace: Int,
    val enterText: Int,
    val shiftOn: Int,
    val shiftOnText: Int,
    val toneBg: Int,
    val toneText: Int,
    val viSpecialBg: Int,
    val candText: Int,
    val candPhraseText: Int,
    val candSelectedBg: Int,
    val candSelectedBorder: Int,
    val composingText: Int,
    val toolbarText: Int,
    val toolbarBg: Int,
    val aiChipBg: Int,
    val aiChipText: Int,
    val aiChipBorder: Int,
    val aiPrimaryBg: Int,
    val aiPrimaryText: Int,
    val aiEqBg: Int,
    val aiEqText: Int,
    val aiTranslateBg: Int,
    val aiTranslateText: Int,
    val hwCanvasBg: Int,
    val hwInk: Int,
    val hwGrid: Int,
    val hwBorder: Int,
    val hwHint: Int,
    val hwBarBg: Int,
    val hwBarText: Int,
    val hwBarAccent: Int,
    val panelBg: Int,
    val isDark: Boolean,
    val keyRadiusDp: Float = 6f,
    val keyHeightDp: Float = 46f,
    val keyFontSp: Float = 18f,
    val candFontSp: Float = 15f,
    val candSingleSp: Float = 22f,
) {
    companion object {
        fun light(): ThemeTokens = ThemeTokens(
            keyboardBg = 0xFFF8F8F8.toInt(),
            keyNormal = 0xFFFFFFFF.toInt(),
            keyUtility = 0xFFE8E8E8.toInt(),
            keyAccent = 0xFF2B6CB0.toInt(),
            keyPressed = 0xFFC8C8C8.toInt(),
            keyBorder = 0xFFE0E0E0.toInt(),
            keySpace = 0xFFF5F5F5.toInt(),
            enterText = 0xFF2B6CB0.toInt(),
            shiftOn = 0xFF1A1A1A.toInt(),
            shiftOnText = 0xFFFFFFFF.toInt(),
            toneBg = 0xFFEEF4FF.toInt(),
            toneText = 0xFF2B6CB0.toInt(),
            viSpecialBg = 0xFFF7F3FF.toInt(),
            candText = 0xFF1A1A1A.toInt(),
            candPhraseText = 0xFF666666.toInt(),
            candSelectedBg = 0xFFEEF4FF.toInt(),
            candSelectedBorder = 0xFF2B6CB0.toInt(),
            composingText = 0xFF2B6CB0.toInt(),
            toolbarText = 0xFF555555.toInt(),
            toolbarBg = 0xFFF8F8F8.toInt(),
            aiChipBg = 0xFFFFFFFF.toInt(),
            aiChipText = 0xFF333333.toInt(),
            aiChipBorder = 0xFFDDDDDD.toInt(),
            aiPrimaryBg = 0xFF1A1A1A.toInt(),
            aiPrimaryText = 0xFFFFFFFF.toInt(),
            aiEqBg = 0xFFF3EEFF.toInt(),
            aiEqText = 0xFF6B46C1.toInt(),
            aiTranslateBg = 0xFFEEF4FF.toInt(),
            aiTranslateText = 0xFF2B6CB0.toInt(),
            hwCanvasBg = 0xFFFAFAFA.toInt(),
            hwInk = 0xFF1A1A1A.toInt(),
            hwGrid = 0xFFE0E0E0.toInt(),
            hwBorder = 0xFFD0D0D0.toInt(),
            hwHint = 0xFFCCCCCC.toInt(),
            hwBarBg = 0xFFF0F0F0.toInt(),
            hwBarText = 0xFF333333.toInt(),
            hwBarAccent = 0xFF2B6CB0.toInt(),
            panelBg = 0xFFFFFFFF.toInt(),
            isDark = false,
        )

        /** 对齐 参考效果.html @media (prefers-color-scheme: dark) */
        fun dark(): ThemeTokens = ThemeTokens(
            keyboardBg = 0xFF1E1E1E.toInt(),
            keyNormal = 0xFF2A2A2A.toInt(),
            keyUtility = 0xFF333333.toInt(),
            keyAccent = 0xFF2B6CB0.toInt(),
            keyPressed = 0xFF3A3A3A.toInt(),
            keyBorder = 0xFF3A3A3A.toInt(),
            keySpace = 0xFF333333.toInt(),
            enterText = 0xFF2B6CB0.toInt(),
            shiftOn = 0xFFE8E8E8.toInt(),
            shiftOnText = 0xFF1A1A1A.toInt(),
            toneBg = 0xFF1A2A3A.toInt(),
            toneText = 0xFF7CB3FF.toInt(),
            viSpecialBg = 0xFF2A1F3A.toInt(),
            candText = 0xFFE8E8E8.toInt(),
            candPhraseText = 0xFF999999.toInt(),
            candSelectedBg = 0xFF1A2A3A.toInt(),
            candSelectedBorder = 0xFF2B6CB0.toInt(),
            composingText = 0xFF7CB3FF.toInt(),
            toolbarText = 0xFFAAAAAA.toInt(),
            toolbarBg = 0xFF242424.toInt(),
            aiChipBg = 0xFF2A2A2A.toInt(),
            aiChipText = 0xFFAAAAAA.toInt(),
            aiChipBorder = 0xFF3A3A3A.toInt(),
            aiPrimaryBg = 0xFFE8E8E8.toInt(),
            aiPrimaryText = 0xFF1A1A1A.toInt(),
            aiEqBg = 0xFF2A1F3A.toInt(),
            aiEqText = 0xFFB794F6.toInt(),
            aiTranslateBg = 0xFF1A2A3A.toInt(),
            aiTranslateText = 0xFF7CB3FF.toInt(),
            hwCanvasBg = 0xFF1E1E1E.toInt(),
            hwInk = 0xFFE8E8E8.toInt(),
            hwGrid = 0xFF2E2E2E.toInt(),
            hwBorder = 0xFF3A3A3A.toInt(),
            hwHint = 0xFF444444.toInt(),
            hwBarBg = 0xFF2A2A2A.toInt(),
            hwBarText = 0xFFCCCCCC.toInt(),
            hwBarAccent = 0xFF2B6CB0.toInt(),
            panelBg = 0xFF1E1E1E.toInt(),
            isDark = true,
        )

        fun from(context: Context): ThemeTokens {
            val night = context.resources.configuration.uiMode and Configuration.UI_MODE_NIGHT_MASK
            // 系统夜间：即使 Application 使用 Light Theme，uiMode 仍会反映当前夜间状态
            return if (night == Configuration.UI_MODE_NIGHT_YES) dark() else light()
        }
    }
}
