[package]
name = "yc-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "yc-cli"
path = "src/main.rs"

[dependencies]
yc-ffi = { path = "../yc-ffi", features = ["data"] }
yc-types = { path = "../yc-types" }
yc-handwriting = { path = "../yc-handwriting" }
yc-theme = { path = "../yc-theme" }
